version: 2.1

jobs:
  rspec_and_coverage:
    resource_class: small
    docker:
      - image: cimg/ruby:2.7.1
      - image: circleci/redis:6.0.6
    working_directory: ~/sidekiq-dup-guard
    steps:
      - checkout

      - run:
          name: check env
          command: |
            echo $PWD
            echo $Dummy
            A=$Dummy
            echo $A
            echo $Dummy > coverage/dummy
            echo $A > coverage/dummy_a
            echo Dummy
            echo $CIRCLE_BRANCH
            ruby script.rb

      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: Run Rspec
          command: bundle exec rspec

      - store_artifacts:
          path: coverage

workflows:
  version: 2.1
  checks:
    jobs:
      - rspec_and_coverage
