version: 2.1

jobs:
  rspec_and_coverage:
    resource_class: small
    docker:
      - image: cimg/ruby:2.7.1
      - image: circleci/redis:6.0.6
    working_directory: ~/sidekiq-dup-guard
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: Run Rspec
          command: bundle exec rspec

      - store_artifacts:
          path: coverage

  build_and_push_gem:
    resource_class: small
    docker:
      - image: cimg/ruby:2.7.1
    working_directory: ~/sidekiq-dup-guard
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: Build Gem
          command: gem build sidekiq-dup-guard.gemspec

      - run:
          name: Push Gem
          command: |
            TAG=${CIRCLE_TAG//v}
            gem push sidekiq-dup-guard-$TAG.gem

workflows:
  version: 2.1
  checks:
    jobs:
      - rspec_and_coverage:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build_and_push_gem:
          requires:
            - rspec_and_coverage
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
